### ISSUE TITLE
SDGs Selection

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#330]
- ❓an option for decreasing amount of the SDG data - just img and motto, without desc - shorten NCA procedure

**NICE TO HAVE**:
  - to add icons of the selected SDGs in the status bar

**Comment by mprinc** [comment]
Object: `window.localStorage`

**Comment by sinisarudan** [comment]
**DONE**
  - disable double selection: **preloading from server** if there are old selections

**Comment by sinisarudan** [comment]
- your closest participant (is described in #467)
- others issue elements are done
