### ISSUE TITLE
Map of the created performance

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#332]
- showing each performance
- hiding texts of the performances (just player and card Human ID) - Grotowski inner dreaming
- deciding which performance to perform
-

**Comment by mprinc** [comment]
Use FDB (Umea project as a reference):

+ /Users/sasha/Documents/data/development/FDB/fdGraph
+ /Users/sasha/Documents/data/development/FDB/FDB.code-workspace

**Comment by sinisarudan** [comment]
migrated to #361

**Comment by sinisarudan** [comment]
migrated to #361
