### ISSUE TITLE
Provide unit & e2e tests

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/colabo#367]
related to #383 
- Make test framework working
  - both for unit and e2e tests
  - both for backend and frontend unit tests
- cover components that we are already using/sharing
  - colaboflow, topichat, rima
- cover components that are critical for next demo
  - dialogame, sdg, ...

**Comment by sinisarudan** [comment]
migrated to #383

**Comment by sinisarudan** [comment]
@mprinc why is this closed?
we still haven't finished it. Just started
