### ISSUE TITLE
Finish Request Similarity Suggestions

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#388]
![image](https://user-images.githubusercontent.com/1769627/48290258-7f6c2a80-e472-11e8-9213-91176824fa74.png)
- is it sending now to @beviah code really requests?
- is it receiving?
- how we see that it received all?
- sent/received
-

**Comment by mprinc** [comment]
All finished, except getting initial confirmation, that the task is sent to the service, and waiting for the response: #393
