### ISSUE TITLE
sdg can unselect but not select new/submit

### ISSUE THREAD

**Issue by beviah** [Cha-OS/colabo#419]
bug or feature?

**Comment by mprinc** [comment]
elaborate, not sure I understand the scenario?

**Comment by sinisarudan** [comment]
no clear to me either?
you mean - if user already selected the SDGs and later comes to the selection page, 
he can still change select/unselect switches but cannot re-submit.

If yes, that's what we talked about earlier. Should we allow him to resubmit at all.
probably depending on a current state in the session, e.g. if the whole group is in the selection phase, he could, if we go to the next phase, he shouldn't be able. 
OK?

Yet we could still disable those switches, when we don't want to allow user to resubmit

**Comment by beviah** [comment]
yep, that's it.. so then disable changing after it is submitted..

**Comment by sinisarudan** [comment]
Solved, part of the commit https://github.com/Cha-OS/colabo/commit/c5aa4a49f26a891359a51d313c4480b534178c5d
will be visible in the next build
