### ISSUE TITLE
Statistics for CFlow Audit

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/colabo#429]
You will get an array/set of different actions (names) and for each they will provide a set of parameters and their values (number

```json
{
  "loadFromCache": {
    "parameters": {
      "count": 10,
      "duration": 3,
     // ...
    }
  },
  "loadWithoutCache": {
    "parameters": {
      "count": 20,
      "duration": 25,
     // ...
    }
  }
  // ...
}
```

You should show a legend made of parameters, and user can choose any of them and the graph will be visualized with that property.

**Comment by sinisarudan** [comment]
@mprinc : Please, provide clear and detailed description of the request .... 
some errors in writing still exist and it's not clearly compared to the current state

**Comment by sinisarudan** [comment]
Done
`colabo/src/frontend/dev_puzzles/flow/audit/lib/audit-form`
in the commit https://github.com/Cha-OS/colabo/commit/bb37405cd5657a44daeffc360f0d24d2f9638a38

**Comment by sinisarudan** [comment]
Done
`colabo/src/frontend/dev_puzzles/flow/audit/lib/audit-form`
in the commit https://github.com/Cha-OS/colabo/commit/bb37405cd5657a44daeffc360f0d24d2f9638a38

**Comment by mprinc** [comment]
![image](https://user-images.githubusercontent.com/996001/49339776-90056000-f62e-11e8-9e5b-e0201049ea45.png)
