### ISSUE TITLE
remove NCA app and create it as a fresh Puzzle-built

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#503]
- right now it often misleads us to edit its files instead of the expected files (that our replicated in it)
- as @mprinc suggested, we would make a new `nca` branch and leave it there and delete it in the main branch
- we will later rebuild apps like NCA and PSC in a puzzle-built manner
  - migrating all the abstract and reusable functionality to puzzles and just using it both in nca and psc and adding specificities
  - so far some functionality is not migrated and is duplicated between the apps
- **changes done to NCA ⚠️ ☢️  **
  - util/Dialog accidentally deleted from it in the commit: https://github.com/Cha-OS/colabo/commit/fd7088637e93456256629edaaf0c717e44168494
  - ⚠️  this issue is WRONGLY referenced in the https://github.com/Cha-OS/colabo/commit/93e016ffb2a324f8a35a681a1a4b2e8289763f2f commit (there was NO change to NCA in that commit)

**Comment by mprinc** [comment]
Closed with the https://github.com/Cha-OS/colabo/commit/99512d91d3a70d1dfb1a59564264039128f87a7d

**Comment by mprinc** [comment]
The NCA is in the https://github.com/Cha-OS/colabo/tree/apps-nca branch
