### ISSUE TITLE
make UI fields to be wide as the form component

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#561]
so far they are cut in width:
![image](https://user-images.githubusercontent.com/1769627/71177700-d8f57a00-226c-11ea-8abb-31cb0eb4c477.png)

**Comment by mprinc** [comment]
Fixed from:
![image](https://user-images.githubusercontent.com/996001/71531041-ca4e3900-28e4-11ea-8f5e-46d0da703ed7.png)

into:
![image](https://user-images.githubusercontent.com/996001/71531018-b73b6900-28e4-11ea-9846-19399a967b39.png)

Added patch:

```css
.mat-form-field {
  display: block !important;
}
```
