### ISSUE TITLE
sdgs-statistics

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/colabo#577]
it happened after change that sdgs[s].targetId is now ID and not KNODE
so I've changed:
`sdgs[s].targetId).dataContent`
with
`this.sDGsService.getSDG(sdgs[s].targetId).dataContent)`
but it doesn't work:
fit src/frontend/dev_puzzles/moderation/core/moderation-panel/insights/results-visualization/sdgs-statistics/sdgs-statistics.component.ts
http://localhost:8891/results
`if(sdgs[s].targetId && this.sDGsService.getSDG(sdgs[s].targetId) && this.sDGsService.getSDG(sdgs[s].targetId).dataContent){
       this.sDGSelectedNo[ ((this.sDGsService.getSDG(sdgs[s].targetId)).dataContent.humanID as number)-1]++; //TODO: expects the current situation in which humanIDs of SDGs are equal SDG Number.
     }
`

**Comment by mprinc** [comment]
this.SDGs.data je prazno

![clipboard_image_1dd13347d8e](https://user-images.githubusercontent.com/996001/71567255-d53ad200-2a7a-11ea-99b4-d902d9a8acb1.jpg)

**Comment by sinisarudan** [comment]
closed by 1de949edef
